mise a jour du Dockerfile
CQEN-QDCE/ceai-cqen-keycloak pull request #15
Opened 2024-10-28 11:42 UTC by chrispelmcn

2024-10-29 13:56 UTC, gagf01 commented on Dockerfile
> +RUN /opt/keycloak/bin/kc.sh build --health-enabled=true --metrics-enabled=true --features=hostname:v2 --http-relative-path=/ --http-management-relative-path=/
D'après la documentation https://www.keycloak.org/server/features hostname:v2 est activé par défaut, donc il pourrait être enlevé ici. Par contre, comme discuté, il faudrait rajouter token-exchange qui lui est désactivé par défaut.

2024-11-01 14:39 UTC, gagf01 requested changes

2024-11-01 14:39 UTC, gagf01 commented on Dockerfile
> +RUN /opt/keycloak/bin/kc.sh build --health-enabled=true --metrics-enabled=true --features=token-exchange --http-relative-path=/ --http-management-relative-path=/
Enlever `--http-relative-path=/ --http-management-relative-path=/` puisque ce sont déjà les valeurs par défaut de ces paramètres.

https://www.keycloak.org/server/all-config?f=build

2024-11-01 18:17 UTC, chrispelmcn commented on Dockerfile
> +RUN /opt/keycloak/bin/kc.sh build --health-enabled=true --metrics-enabled=true --features=hostname:v2 --http-relative-path=/ --http-management-relative-path=/
Changement effectué

2024-11-01 18:17 UTC, chrispelmcn commented on Dockerfile
> +RUN /opt/keycloak/bin/kc.sh build --health-enabled=true --metrics-enabled=true --features=token-exchange --http-relative-path=/ --http-management-relative-path=/
Changement effectué

2024-11-01 18:52 UTC, merged