integration github actions
CQEN-QDCE/ceai-cqen-keycloak pull request #9
Opened 2024-09-05 19:20 UTC by chrispelmcn

2024-09-11 17:04 UTC, gagf01 requested changes

2024-09-11 17:04 UTC, gagf01 commented on .github/workflows/run_keycloak_tests.yml
> +        ./run_tests.sh
Cette étape m'apparait trop longue. Est-ce que tu pourrais séparer l’exécution de Docker-Compose du reste? Tu peux utiliser la propriété needs pour dire au tests d'attendre que les docker soit levés.

2024-09-11 17:04 UTC, gagf01 commented on .github/workflows/run_keycloak_tests.yml
> +      uses: actions/checkout@v2
Assures-toi d'utiliser les versions les plus récentes des actions: https://github.com/actions/checkout

2024-09-13 13:05 UTC, chrispelmcn commented on .github/workflows/run_keycloak_tests.yml
> +      - 'feature/*'
Corrigé

2024-09-13 13:05 UTC, chrispelmcn commented on .github/workflows/run_keycloak_tests.yml
> +        ./run_tests.sh
corrigé

2024-09-13 13:06 UTC, chrispelmcn commented on .github/workflows/run_keycloak_tests.yml
> +      uses: actions/checkout@v2
j'ai replavé par la version @v4

2024-09-16 14:54 UTC, gagf01 approved these changes

2024-09-16 17:54 UTC, merged